In [ ]:
# !pip install tensorflow-gpu

In [ ]:
# !nvidia-smi

In [ ]:
!pip install BnVec
!git clone https://github.com/banglakit/bengali-stemmer.git
!python -m pip install --upgrade pip
%cd bengali-stemmer
!pip install flake8

In [ ]:
!pip3 install ktrain

#Load Files

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
from pandas import DataFrame
from BnVec import CountVectorizer
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split


In [ ]:
from bengali_stemmer.rafikamal2014 import RafiStemmer
stemmer = RafiStemmer()

In [ ]:
data = pd.read_csv('/content/data.csv')
stopwords = pd.read_csv('/content/stopwords_bangla.csv')

In [ ]:
# data

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
texts = list(data['Text'])
set_stop = set(stopwords['Words'])

In [ ]:
def clean_punct(sentence):
    cleaned = re.sub(r'[?|!|\'|"|#|।|’|‘]', r'', sentence)
    cleaned1 = re.sub(r'[.|,|(|)|\|/]', r'', cleaned)
    # cleaned = re.sub(r'[০|১|২|৩|৪|৫|৬|৭|৮|৯]', r'', cleaned1)
    cleaned1 = re.sub(r'[-|=]', r' ', cleaned1)
    return cleaned1

In [ ]:
def pre_process(data):
    i=0
    str1=' '
    final_string = []
    final_words = []
    all_negative_words = []
    s=''

    for sentence in data:
        filtered_sentence = []
        for w in str(sentence).split():
            for cleaned_word in clean_punct(w).split():
                if len(cleaned_word)>2:
                   # print(cleaned_word)
                    if((cleaned_word) not in set_stop):
                        # s = stemmer.stem_word(cleaned_word)
                        s = cleaned_word
                        #print(s)
                        if len(s)>2:
                            final_words.append(s)
                            filtered_sentence.append(s)
                    else:
                        continue
                else:
                    continue

        str1 = " ".join(filtered_sentence)
        final_string.append(str1)
    return final_string

# pun = set(['(' , ')' ,'.' , '!' , '|' , '#' , ',' , '?' , '[' , ']' , '/' , '\' , '-'  , '"' , "'" ])

# pun = set([ '।' ])

# def clear_punc(texts):

#   for i in range(len(texts)):
#     tmp = ""
#     w = str(texts[i])
#     s = w.split()
#     size = len(s)
#     for j in range(size):
#       if s[j] in pun:
#         #print(s[j])
#         continue
#       #print(s[j])
#       tmp += s[j]
#       if j + 1 < size:
#         tmp += ' '
#     texts[i] = tmp

#   return texts
# x = clear_punc(texts)

In [ ]:
import re
re.compile('<title>(.*)</title>')
texts = pre_process(texts)

In [ ]:
# texts

**Space Removing**

In [ ]:
ambi_word = list(data['ambiguous_word'])
for word in ambi_word:
  if word == 'কাটা ':
    word = 'কাটা'
  if word == 'কড়া ':
    word = 'কড়া'
  if word == 'বল ':
    word = 'বল'
  

In [ ]:
def unique(list1): 
    unique_list = [] 
    for x in list1: 
        if x not in unique_list: 
            unique_list.append(x) 
    for x in unique_list: 
        print(x)

## Append ambiguous word to the text

In [ ]:
# texts

In [ ]:
for i in range(len(texts)):
	texts[i] = str(texts[i])

for i in range(len(ambi_word)):
	ambi_word[i] = str(ambi_word[i])

In [ ]:
for i in range(len(texts)):
  texts[i] = texts[i] + " " + data['ambiguous_word'][i]

In [ ]:
texts

In [ ]:
#  unique(ambi_word)
# for i in range(len(text)):
# 	s = text[i] + " ";

# print(len(set(s.split())))

In [ ]:
Max_len = 0
for i in range(len(texts)):
  Max_len = max(Max_len,len(texts[i]))
print(Max_len)

127


**Count Vectorize**

In [ ]:
from pandas import DataFrame
from BnVec import CountVectorizer
cv = CountVectorizer()
x_ambi = cv.fit_transform(ambi_word) # x is the word features
# x_ambi

In [ ]:
text_word = list(data['Text'])
x_text = cv.fit_transform(data['Text'].values.astype('U'))
# x_text = cv.fit_transform(text_word)
# x_text

In [ ]:
x = np.concatenate((x_text, x_ambi), 1)

In [ ]:
# x

# **Vectorization**

In [ ]:
macronum=sorted(set(data['meaning']))
macro_to_id = dict((note, number) for number, note in enumerate(macronum))

def fun(i):
    return macro_to_id[i]

label=data['meaning'].apply(fun)

In [ ]:
y= label
# y

# **Import libraries**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_validate 
from collections import Counter
from sklearn.metrics import accuracy_score

In [ ]:
#Splitting dataset
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

# **SVM**

In [ ]:
# from sklearn.preprocessing import StandardScaler
# cols = X_train.columns
# scaler = StandardScaler()

# X_train = scaler.fit_transform(X_train)

# X_test = scaler.transform(X_test)
# X_train = pd.DataFrame(X_train, columns=[cols])
# X_test = pd.DataFrame(X_test, columns=[cols])
# X_train.describe()

In [ ]:
from sklearn.svm import SVC

# import metrics to compute accuracy
from sklearn.metrics import accuracy_score

# instantiate classifier with default hyperparameters
svc=SVC() 

# fit classifier to training set
svc.fit(X_train,y_train)

# make predictions on test set
y_pred=svc.predict(X_test)

# compute and print accuracy score
print('Model accuracy score with default hyperparameters: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with default hyperparameters: 0.3765


Run SVM with linear kernel and C=1.0

In [ ]:
from sklearn.svm import SVC
# instantiate classifier with linear kernel and C=1.0

linear_svc=SVC(kernel='linear', C=1.0) 


# fit classifier to training set
linear_svc.fit(X_train,y_train)


# make predictions on test set
y_pred_test=linear_svc.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_test)))

Model accuracy score with linear kernel and C=1.0 : 0.7512


Run SVM with linear kernel and C=100.0

In [ ]:
# instantiate classifier with linear kernel and C=100.0
linear_svc100=SVC(kernel='linear', C=100.0) 


# fit classifier to training set
linear_svc100.fit(X_train, y_train)


# make predictions on test set
y_pred=linear_svc100.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with linear kernel and C=100.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with linear kernel and C=100.0 : 0.7512


Run SVM with linear kernel and C=1000.0

In [ ]:
# instantiate classifier with linear kernel and C=1000.0
linear_svc1000=SVC(kernel='linear', C=1000.0) 


# fit classifier to training set
linear_svc1000.fit(X_train, y_train)


# make predictions on test set
y_pred=linear_svc1000.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with linear kernel and C=1000.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with linear kernel and C=1000.0 : 0.7512


Compare the train-set and test-set accuracy

In [ ]:
y_pred_train = linear_svc.predict(X_train)
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))



Training-set accuracy score: 0.9957


In [ ]:

print('Training set score: {:.4f}'.format(linear_svc.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(linear_svc.score(X_test, y_test)))

Training set score: 0.9957
Test set score: 0.7512


Run SVM with polynomial kernel 

In [ ]:
# instantiate classifier with polynomial kernel and C=1.0
poly_svc=SVC(kernel='poly', C=1.0) 


# fit classifier to training set
poly_svc.fit(X_train,y_train)


# make predictions on test set
y_pred=poly_svc.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with polynomial kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with polynomial kernel and C=1.0 : 0.0547


Run SVM with polynomial kernel and C=100.0¶

In [ ]:
# instantiate classifier with polynomial kernel and C=100.0
poly_svc100=SVC(kernel='poly', C=100.0) 


# fit classifier to training set
poly_svc100.fit(X_train, y_train)


# make predictions on test set
y_pred=poly_svc100.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with polynomial kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with polynomial kernel and C=1.0 : 0.2952


Run SVM with sigmoid kernel

In [ ]:
# instantiate classifier with sigmoid kernel and C=1.0
sigmoid_svc=SVC(kernel='sigmoid', C=1.0) 


# fit classifier to training set
sigmoid_svc.fit(X_train,y_train)


# make predictions on test set
y_pred=sigmoid_svc.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with sigmoid kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with sigmoid kernel and C=1.0 : 0.5738


Run SVM with sigmoid kernel and C=100.0

In [ ]:
# instantiate classifier with sigmoid kernel and C=100.0
sigmoid_svc100=SVC(kernel='sigmoid', C=100.0) 


# fit classifier to training set
sigmoid_svc100.fit(X_train,y_train)


# make predictions on test set
y_pred=sigmoid_svc100.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with sigmoid kernel and C=100.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with sigmoid kernel and C=100.0 : 0.7927


# Confusion matrix 

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_test)

print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[3 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 4 0]
 [0 0 0 ... 0 0 0]]

True Positives(TP) =  3

True Negatives(TN) =  2

False Positives(FP) =  0

False Negatives(FN) =  0
